# Use uma imagem do Node.js como base
FROM node:lts

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Exponha a porta 4200 para acesso externo
EXPOSE 4200

# Opcional: Instale bibliotecas adicionais, se necessário.
# Por exemplo:
# RUN npm install -g pnpm
# RUN corepack enable